INSERT INTO `product` (`product_id`, `product_name`, `product_price`, `product_image_link`, `product_stock`, `product_category`) VALUES

(24, 'Wuam ultrices rutrum', 320, '/e-shopper/assets/themes/images/ladies/24m.jpg', 10, 'Men'),
(25, 'Praesent tempor sem', 28, '/e-shopper/assets/themes/images/ladies/25m.jpg', 10, 'Men'),
(26, 'Wuam ultrices rutrum', 320, '/e-shopper/assets/themes/images/ladies/26m.jpg', 10, 'Men'),
(27, 'Praesent tempor sem sodales', 49, '/e-shopper/assets/themes/images/ladies/27m.jpg', 5, 'Men'),
(28, 'Fusce id molestie massa', 35, '/e-shopper/assets/themes/images/ladies/28w.jpg', 2, 'women'),
(29, 'Praesent tempor sem sodales', 49, '/e-shopper/assets/themes/images/ladies/29m.jpg', 5, 'Men'),
(30, 'Fusce id molestie massa', 35, '/e-shopper/assets/themes/images/ladies/30w.jpg', 2, 'women'),
(31, 'Luctus quam ultrices', 261, '/e-shopper/assets/themes/images/ladies/31m.jpg', 5, 'Men'),
(32, 'Phasellus consequat', 562, '/e-shopper/assets/themes/images/ladies/32w.jpg', 1, 'women'),
(33, 'Erat gravida', 52, '/e-shopper/assets/themes/images/ladies/33w.jpg', 56, 'women'),
(34, 'Suspendisse aliquet', 54, '/e-shopper/assets/themes/images/ladies/34w.jpg', 17, 'women'),
(35, 'Nam imperdiet', 15, '/e-shopper/assets/themes/images/ladies/35m.jpg', 5, 'Men'),
(36, 'Congue diam congue', 58, '/e-shopper/assets/themes/images/ladies/36m.jpg', 10, 'Men'),
(37, 'Phasellus consequat', 562, '/e-shopper/assets/themes/images/ladies/37m.jpg', 1, 'Men'),
(38, 'Suspendisse aliquet', 54, '/e-shopper/assets/themes/images/ladies/38m.jpg', 17, 'Men'),
(39, 'Wuam ultrices rutrum', 320, '/e-shopper/assets/themes/images/ladies/39s.jpg', 10, 'sport'),
(40, 'Praesent tempor sem', 28, '/e-shopper/assets/themes/images/ladies/40s.jpg', 10, 'sport'),
(41, 'Wuam ultrices rutrum', 320, '/e-shopper/assets/themes/images/ladies/41s.jpg', 10, 'sport'),
(42, 'Praesent tempor sem sodales', 49, '/e-shopper/assets/themes/images/ladies/42s.jpg', 5, 'sport'),
(43, 'Fusce id molestie massa', 35, '/e-shopper/assets/themes/images/ladies/43s.jpg', 2, 'sport'),
(44, 'Praesent tempor sem sodales', 49, '/e-shopper/assets/themes/images/ladies/44s.jpg', 5, 'sport'),
(45, 'Fusce id molestie massa', 35, '/e-shopper/assets/themes/images/ladies/45s.jpg', 2, 'sport'),
(46, 'Luctus quam ultrices', 261, '/e-shopper/assets/themes/images/ladies/46s.jpg', 5, 'sport'),
(47, 'Phasellus consequat', 562, '/e-shopper/assets/themes/images/ladies/47s.jpg', 1, 'sport'),
(48, 'Erat gravida', 52, '/e-shopper/assets/themes/images/ladies/48s.jpg', 56, 'sport'),
(49, 'Suspendisse aliquet', 54, '/e-shopper/assets/themes/images/ladies/49s.jpg', 17, 'sport')

